name: renv_cache

on:
  push:
     branches: master

jobs:
  renv_cache:
    runs-on: ${{ matrix.config.os }}

    name: ${{ matrix.config.os }} (${{ matrix.config.r }})

    strategy:
      fail-fast: false
      matrix:
        config:
        - { os: windows-latest, r: 'release'}
        - { os: macOS-latest,   r: 'release'}
        - { os: ubuntu-20.04,  r: 'release', rspm: "https://packagemanager.rstudio.com/cran/__linux__/focal/latest" }
        
    env:
      R_REMOTES_NO_ERRORS_FROM_WARNINGS: true
      CRAN: ${{ matrix.config.rspm }}

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2
    - uses: r-lib/actions/setup-r@master
      with:
        r-version: ${{ matrix.config.r }}
    - name: Install system dependencies
      if: startsWith(runner.os, 'Linux')
      run: |-
        sudo apt-get update && \
        sudo apt-get install -y --no-install-recommends \
        libcurl4-openssl-dev \
        libssl-dev \
        zlib1g-dev && \
        sudo apt-get clean && \
        sudo rm -rf /var/lib/apt/lists/*
    - uses: actions/cache@v2
      if: startsWith(runner.os, 'Linux')
      with:
        path: ~/.local/share/renv
        key: ${{ runner.os }}-renv-${{ hashFiles('**/renv.lock') }}
        restore-keys: |
          ${{ runner.os }}-renv-
    - uses: actions/cache@v2
      if: startsWith(runner.os, 'macOS')
      with:
        path: ~/Library/Application Support/renv
        key: ${{ runner.os }}-renv-${{ hashFiles('**/renv.lock') }}
        restore-keys: |
          ${{ runner.os }}-renv-
    - uses: actions/cache@v2
      if: startsWith(runner.os, 'Windows')
      with:
        path: ~\AppData\Local\renv
        key: ${{ runner.os }}-renv-${{ hashFiles('**/renv.lock') }}
        restore-keys: |
          ${{ runner.os }}-renv-
    - name: Install Package Dependencies
      run: |-
        Rscript -e "install.packages('renv'); renv::restore(confirm = FALSE)"
    - name: Run rscript
      run: |
        Rscript -e "source('02-workflow.R')"
